<a href="https://colab.research.google.com/github/MSebastian2021/Artificial_Neural_Networks_Tests/blob/main/Regression_Housing_mine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from sklearn.datasets import load_boston

boston_dataset = load_boston()
boston_dataset

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

{'DESCR': ".. _boston_dataset:\n\nBoston house prices dataset\n---------------------------\n\n**Data Set Characteristics:**  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate p

In [ ]:
print('data is: {}'.format(boston_dataset.data))
print('independent variable names are: {}'.format(boston_dataset.feature_names))
print('labels or prices: {}'.format(boston_dataset.target))

data is: [[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
independent variable names are: ['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']
labels or prices: [24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28. 

In [ ]:
df = pd.DataFrame(boston_dataset.data, columns=boston_dataset.feature_names)
df['Price'] = boston_dataset.target
df.head(n=10)

CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575   65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421   78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185   61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998   45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147   54.2  6.0622  3.0  222.0   
5  0.02985   0.0   2.18   0.0  0.458  6.430   58.7  6.0622  3.0  222.0   
6  0.08829  12.5   7.87   0.0  0.524  6.012   66.6  5.5605  5.0  311.0   
7  0.14455  12.5   7.87   0.0  0.524  6.172   96.1  5.9505  5.0  311.0   
8  0.21124  12.5   7.87   0.0  0.524  5.631  100.0  6.0821  5.0  311.0   
9  0.17004  12.5   7.87   0.0  0.524  6.004   85.9  6.5921  5.0  311.0   

   PTRATIO       B  LSTAT  Price  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  
3     18.7  394.63   2.94   33.4  
4     18.7  396.90   5.33   36.2  
5     18.7  394.12   5.21   28.7  
6     15.2  395.60  12.43   22.9  
7     15.2  396.90  19.15   27.1  
8     15.2  386.63  29.93   16.5  
9     15.2  386.71  17.10   18.9

In [ ]:
df.describe(include='all')

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT       Price  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [ ]:
x = df.loc[:, df.columns != 'Price']
y = df.loc[:, df.columns == 'Price']

In [ ]:
# Split the data into training and test set (20% for the test set)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y,test_size = 0.2, random_state = 123) # We use random_state to make sure splitting contains the same data each time.

In [ ]:
#Standardise the data (x_standardised = (x - x_mean)/std_dev)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test) #note that we use the scale set from the training set to transform the test set
df = pd.DataFrame(X_train)
df

0         1         2         3         4         5         6   \
0   -0.401149  3.653859 -1.226095 -0.245698 -1.199016  2.231987 -1.278274   
1    0.702723 -0.486534  0.995482 -0.245698  1.587329  0.176596  1.008537   
2   -0.389296 -0.486534 -1.028718 -0.245698 -0.391243 -1.008059  0.697674   
3   -0.391244 -0.486534 -1.195840 -0.245698 -0.950404  0.487675 -0.399281   
4   -0.403599  2.782197 -1.035921 -0.245698 -1.251491 -0.559197 -0.763742   
..        ...       ...       ...       ...       ...       ...       ...   
399 -0.395821 -0.486534 -1.195840 -0.245698 -0.950404  2.185112 -1.146068   
400  0.149849 -0.486534  0.995482 -0.245698  0.503416  0.287391  0.879904   
401 -0.365143 -0.486534 -0.548961 -0.245698 -0.537485 -0.341868 -0.681559   
402  0.641524 -0.486534  0.995482 -0.245698  1.243229 -1.059195  1.108585   
403  0.113900 -0.486534  0.995482 -0.245698  1.398074 -3.864583  0.676235   

           7         8         9         10        11        12  
0    0.623686 -0.636934 -1.095990 -1.753696  0.388482 -1.266398  
1   -0.806000  1.675027  1.530409  0.808919  0.313998  0.940407  
2   -0.557330 -0.521336 -0.668160 -0.868429  0.433478  0.261930  
3   -0.136278 -0.868130 -0.787002 -0.216127  0.008419 -0.867459  
4    1.654751 -0.752532  0.359819  1.228256  0.433478  0.277382  
..        ...       ...       ...       ...       ...       ...  
399 -0.136278 -0.868130 -0.787002 -0.216127  0.396673 -1.300111  
400 -0.693513  1.675027  1.530409  0.808919  0.425942  0.822411  
401  0.437816 -0.521336 -0.721639  0.529361  0.433478 -0.719964  
402 -1.032987  1.675027  1.530409  0.808919  0.433478  1.513530  
403 -1.017626  1.675027  1.530409  0.808919 -0.027403 -0.801438  

[404 rows x 13 columns]

Architecture based on two Dense layers, the first with 128 and the second with 64 neurons, both using a ReLU (Rectified Linear Unit) activation function. 

A dense layer with a linear activation will be used as output layer.


In [ ]:
import tensorflow as tf
from tensorflow import keras

model = keras.Sequential()

#add first layer and first hidden layer, units = number of nodes / neurons
model.add(tf.keras.layers.Dense(units=128, activation='relu'))

#add second hidden layer
model.add(tf.keras.layers.Dense(units=64, activation='relu'))

In [ ]:
#add the output layer
model.add(tf.keras.layers.Dense(units=1, activation='linear'))

In [ ]:
#Compilation
model.compile(optimizer = 'adam', loss ='mse', metrics = ['accuracy'])

In [ ]:
#Training, should not give a lot of epochs to a small dataset
history = model.fit(X_train, y_train, epochs = 100, verbose=2)

Epoch 1/100
13/13 - 0s - loss: 0.4119 - accuracy: 0.0000e+00 - 29ms/epoch - 2ms/step
Epoch 2/100
13/13 - 0s - loss: 0.4114 - accuracy: 0.0000e+00 - 28ms/epoch - 2ms/step
Epoch 3/100
13/13 - 0s - loss: 0.3949 - accuracy: 0.0000e+00 - 29ms/epoch - 2ms/step
Epoch 4/100
13/13 - 0s - loss: 0.3957 - accuracy: 0.0000e+00 - 30ms/epoch - 2ms/step
Epoch 5/100
13/13 - 0s - loss: 0.3813 - accuracy: 0.0000e+00 - 29ms/epoch - 2ms/step
Epoch 6/100
13/13 - 0s - loss: 0.3894 - accuracy: 0.0000e+00 - 42ms/epoch - 3ms/step
Epoch 7/100
13/13 - 0s - loss: 0.4036 - accuracy: 0.0000e+00 - 34ms/epoch - 3ms/step
Epoch 8/100
13/13 - 0s - loss: 0.4272 - accuracy: 0.0000e+00 - 28ms/epoch - 2ms/step
Epoch 9/100
13/13 - 0s - loss: 0.4217 - accuracy: 0.0000e+00 - 30ms/epoch - 2ms/step
Epoch 10/100
13/13 - 0s - loss: 0.3981 - accuracy: 0.0000e+00 - 34ms/epoch - 3ms/step
Epoch 11/100
13/13 - 0s - loss: 0.3846 - accuracy: 0.0000e+00 - 30ms/epoch - 2ms/step
Epoch 12/100
13/13 - 0s - loss: 0.4064 - accuracy: 0.0000e+00 -

In [ ]:
#Evaluation
loss = model.evaluate(X_test, y_test)
loss

4/4 [==============================] - 0s 3ms/step - loss: 13.0555 - accuracy: 0.0000e+00


[13.05546760559082, 0.0]